# Generated by Django 4.2.1 on 2023-05-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_1', models.CharField(max_length=15)),
                ('apellido_2', models.CharField(max_length=15)),
            ],
        ),
    ]
