# Generated by Django 4.2.1 on 2023-05-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
    ]
