# Generated by Django 4.2.1 on 2023-05-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_estudiante_curso_alter_estudiante_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_2',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
